apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
spec:
  containers:
  - name: nfs-server
    image: itsthenetwork/nfs-server-alpine
    env:
      - name: SHARED_DIRECTORY
        value: /export
    volumeMounts:
      - name: nfs-data
        mountPath: /export
  volumes:
  - name: nfs-data
    hostPath:
      path: /data/kind/nfs
      type: DirectoryOrCreate
